const mongoose = require('mongoose');

const StoreSchema = mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    StoreName: String,
    StoreIncharge: String,
    Branch: String,
    EstablishedYear: String,
    StorePhone1: String,
    StorePhone2: String,
    StoreCoordinates: String,
    CanDeliver: String,
    DeliveryRadius: String,
    DeliveryFee: String,
    AddressLine1: String,
    AddressLine2: String,
    Landmark: String,
    City: String,
    State: String,
    Country: String,
    PostalCode: String,
    RegistrationNo: String,
    CertificateNo: String,
    UserId: { type: mongoose.Schema.Types.ObjectId, ref: 'StoreUser', required: false },
    PayeeName: String,
    BankACNo: String,
    IFSCCode: String,
    BankBranch: String,
    AccountType: Number,
    BankName: String,
    StoreImagePath: String,
    StoreTag: String,
    StoreStatus: String,
    storeplan: String,
    StoreUsersLimit: Number,
    StorePin: Number,
    Stock: [],
    StoreTimings: [],
    StoreOffer: [],
    GlobalOffer: [],
    StoreDeliveryFee: []
});

module.exports = mongoose.model('Store', StoreSchema);